# model.py
# ## ------------------------------------------------------------
# GRL 및 피실험자 분류기(Subject Classifier)가 제거된 버전입니다.
# 이제 모델은 순수하게 Action Classification만 수행합니다.
# ## ------------------------------------------------------------


import torch
import torch.nn as nn
import numpy as np
import config
import math
from torch.autograd import Function
import warnings

# [GRL 제거됨] GradientReversalFunction, GradientReversalLayer 클래스 삭제

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (torch.Tensor, float, float, float, float) -> torch.Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


# ## --------------------------------------------------------
# RMSNorm
# ## --------------------------------------------------------
class RMSNorm(nn.Module):
    def __init__(self, d, eps=1e-6):
        super().__init__()
        self.eps = eps
        self.weight = nn.Parameter(torch.ones(d))

    def forward(self, x):
        rsqrt = torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + self.eps)
        return x * rsqrt * self.weight
    

# ## ------------------------------------------------------------
# Attention Pooling
# ## ------------------------------------------------------------
class AttentionPooling(nn.Module):
    def __init__(self, d_model):
        super().__init__()
        self.attention_scorer = nn.Linear(d_model, 1)

    def forward(self, x):
        N, T, J, C = x.shape
        x_reshaped = x.view(N, T * J, C)
        attention_logits = self.attention_scorer(x_reshaped)
        attention_weights = torch.softmax(attention_logits, dim=1)
        context_vector = (x_reshaped * attention_weights).sum(dim=1)
        return context_vector
    

# ## ------------------------------------------------------------
# 2D 학습 가능 Positional Encoding
# ## ------------------------------------------------------------
class SpatioTemporalPositionalEncoding(nn.Module):
    def __init__(self, d_model: int, num_joints: int, max_frames: int, dropout: float = 0.2):
        super().__init__()
        self.dropout = nn.Dropout(p=dropout)
        
        self.temporal_pe = nn.Parameter(torch.zeros(1, max_frames, 1, d_model))
        self.spatial_pe = nn.Parameter(torch.zeros(1, 1, num_joints, d_model))

        trunc_normal_(self.temporal_pe, std=.02)
        trunc_normal_(self.spatial_pe, std=.02)

    def forward(self, x):
        x = x + self.temporal_pe[:, :x.size(1), :, :]
        x = x + self.spatial_pe[:, :, :x.size(2), :]
        return self.dropout(x)


# ## -------------------------------------------------------------------------
# Spatial-Temporal Transformer Block
# ## -------------------------------------------------------------------------
class ST_Transformer_Block(nn.Module):
    def __init__(self, in_features, out_features, num_joints, nhead=4, pos_encoder=None):
        super().__init__()
        self.out_features = out_features
        dim_feedforward = out_features * 2
        self.pos_encoder = pos_encoder
        
        self.input_proj = nn.Linear(in_features, out_features)
        self.norm_proj = RMSNorm(out_features)

        self.num_joints = num_joints

        # >> Slow Fast
        self.spatial_norm1 = RMSNorm(out_features)
        self.spatial_msa = nn.MultiheadAttention(
            embed_dim=out_features, num_heads=nhead, dropout=0.2, batch_first=True
        )
        self.spatial_norm2 = RMSNorm(out_features)
        self.spatial_ffn = nn.Sequential(
            nn.Linear(out_features, dim_feedforward),
            nn.GELU(),
            nn.Dropout(0.2),
            nn.Linear(dim_feedforward, out_features),
            nn.Dropout(0.2)
        )

        # >> Temporal Encoder
        temporal_encoder_layer = nn.TransformerEncoderLayer(
            d_model=out_features, nhead=nhead, dim_feedforward=dim_feedforward,
            activation='gelu', batch_first=True, dropout=0.2
        )
        self.temporal_transformer_encoder = nn.TransformerEncoder(temporal_encoder_layer, num_layers=1)
        self.norm_temporal = RMSNorm(out_features)
        
        # >> Residual
        if in_features != out_features:
            self.residual = nn.Sequential(
                nn.Linear(in_features, out_features),
                RMSNorm(out_features)
            )
        else:
            self.residual = nn.Identity()


    def forward(self, x):
        N, T, J, C_out = x.shape[0], x.shape[1], x.shape[2], self.out_features
        
        res = self.residual(x)
        x_proj = self.norm_proj(self.input_proj(x)) 

        if self.pos_encoder is not None:
            x_proj = self.pos_encoder(x_proj)

        x_spatial_in = x_proj.contiguous().view(N * T, J, C_out)
        
        # MSA
        x_norm1 = self.spatial_norm1(x_spatial_in)
        attn_output, _ = self.spatial_msa(
            x_norm1, x_norm1, x_norm1, average_attn_weights=False
        )
        x_msa_out = x_spatial_in + attn_output 
        
        # FFN
        x_norm2 = self.spatial_norm2(x_msa_out)
        ffn_output = self.spatial_ffn(x_norm2)
        x_spatial_out_NT = x_msa_out + ffn_output 
        
        x_spatial_out = x_spatial_out_NT.view(N, T, J, C_out)

        # Temporal Transformer
        x_reshaped_temporal = x_spatial_out.permute(0, 2, 1, 3).contiguous().view(N * J, T, C_out)
        x_temporal_attn = self.temporal_transformer_encoder(x_reshaped_temporal)

        x_temporal_out = x_temporal_attn.view(N, J, T, C_out).permute(0, 2, 1, 3).contiguous()

        return x_temporal_out + res
    
    

# ## -------------------------------------------------------------------------
# SlowFast Transformer
# ## -------------------------------------------------------------------------
class SlowFast_Transformer(nn.Module):
    def __init__(self,
                 num_joints=config.NUM_JOINTS,
                 num_coords=config.NUM_COORDS,
                 num_classes=config.NUM_CLASSES,
                 fast_dims=config.FAST_DIMS,
                 slow_dims=config.SLOW_DIMS,
                 num_subjects=config.NUM_SUBJECTS,
                 # alpha=1.0 # [GRL 제거됨] alpha 인자 제거
                 ):
        super().__init__()
        
        self.fast_dims = fast_dims
        self.slow_dims = slow_dims
        
        if len(self.fast_dims) != len(self.slow_dims):
            raise ValueError("Fast와 Slow 경로의 블록 수가 동일해야 합니다.")

        # --- 1. Fast Pathway ---
        self.fast_input_projection = nn.Linear(num_coords, fast_dims[0])
        self.fast_blocks = nn.ModuleList()
        for i in range(len(fast_dims) - 1):
            fast_pe = SpatioTemporalPositionalEncoding(
                d_model=fast_dims[i+1],
                num_joints=num_joints,
                max_frames=config.MAX_FRAMES
            )
            self.fast_blocks.append(
                ST_Transformer_Block(
                    in_features=fast_dims[i],
                    out_features=fast_dims[i+1],
                    num_joints=num_joints,
                    pos_encoder=fast_pe
                )
            )

        # --- 2. Slow Pathway ---
        self.slow_input_projection = nn.Linear(num_coords, slow_dims[0])
        self.slow_blocks = nn.ModuleList()

        for i in range(len(slow_dims) - 1):
            slow_pe = SpatioTemporalPositionalEncoding(
                d_model=slow_dims[i+1],
                num_joints=num_joints,
                max_frames=(config.MAX_FRAMES // 2)
            )
            self.slow_blocks.append(
                ST_Transformer_Block(
                    in_features=slow_dims[i],
                    out_features=slow_dims[i+1],
                    num_joints=num_joints,
                    pos_encoder=slow_pe
                )
            )

        # --- 3. Lateral Connection ---
        self.lateral_connections = nn.ModuleList()
        for i in range(len(self.fast_dims)-1):
            self.lateral_connections.append(
                nn.Conv2d(
                    in_channels=fast_dims[i],
                    out_channels=slow_dims[i],
                    kernel_size=(5, 1),
                    stride=(2, 1),           
                    padding=(2, 0)
                )
            )

        self.inv_lateral_connections = nn.ModuleList()
        for i in range(len(self.fast_dims)-1):
            self.inv_lateral_connections.append(
                nn.ConvTranspose2d(
                    in_channels=slow_dims[i],
                    out_channels=fast_dims[i],
                    kernel_size=(5, 1),
                    stride=(2, 1),
                    padding=(2, 0),
                    output_padding=(1, 0)
                )
            )

        # --- 4. Final Classification (최종 분류) ---
        final_fast_dim = fast_dims[-1]
        final_slow_dim = slow_dims[-1]
        combined_dim = final_fast_dim + final_slow_dim

        self.fast_pool = AttentionPooling(d_model=final_fast_dim)
        self.slow_pool = AttentionPooling(d_model=final_slow_dim)

        # [GRL 수정] 행동 분류 헤드만 남김
        self.action_head = nn.Sequential(
            nn.Dropout(p=config.DROPOUT),
            nn.Linear(combined_dim, num_classes)
        )
        
        # [GRL 제거됨] self.grad_reversal 및 self.subject_classifier 삭제
        # self.grad_reversal = GradientReversalLayer(alpha=alpha) 
        # self.subject_classifier = ...

    
    def forward(self, x_fast, x_slow):
        N, _, T_fast, J = x_fast.shape
        _, _, T_slow, _ = x_slow.shape

        x_fast = x_fast.permute(0, 2, 3, 1).contiguous()
        x_slow = x_slow.permute(0, 2, 3, 1).contiguous()
        
        x_fast = self.fast_input_projection(x_fast)
        x_slow = self.slow_input_projection(x_slow)
        
        for i in range(len(self.fast_blocks)):
            # Lateral Connection
            x_fast_permuted = x_fast.permute(0, 3, 1, 2).contiguous()
            fast_to_slow = self.lateral_connections[i](x_fast_permuted)
            fast_to_slow = fast_to_slow.permute(0, 2, 3, 1).contiguous()

            x_slow_permuted = x_slow.permute(0, 3, 1, 2).contiguous()
            slow_to_fast = self.inv_lateral_connections[i](x_slow_permuted)
            slow_to_fast = slow_to_fast.permute(0, 2, 3, 1).contiguous()

            x_slow_combined = x_slow + fast_to_slow
            x_fast_combined = x_fast + slow_to_fast
            
            x_fast = self.fast_blocks[i](x_fast_combined)
            x_slow = self.slow_blocks[i](x_slow_combined)
            
        summary_fast = self.fast_pool(x_fast)
        summary_slow = self.slow_pool(x_slow)

        combined_summary = torch.cat([summary_slow, summary_fast], dim=1)
        
        output_action = self.action_head(combined_summary)

        # [GRL 제거됨] GRL 및 Subject Classifier 호출 로직 삭제
        # reversed_features = self.grad_reversal(combined_summary)
        # output_subject = self.subject_classifier(reversed_features)

        # [수정됨] 행동 예측값 하나만 반환
        return output_action
