# model.py
# ## ------------------------------------------------------------
#
# ## ------------------------------------------------------------


import torch
import torch.nn as nn
import numpy as np
import config
import math
from torch.autograd import Function
import warnings

# ## -----------------------------------------------------------------
# Gradient Reversal Layer (GRL)
# ## -----------------------------------------------------------------
class GradientReversalFunction(Function):
    @staticmethod
    def forward(ctx, input, alpha):
        # alpha 값을 저장하여 backward에서 사용
        ctx.alpha = alpha 
        return input.clone() # 입력 그대로 반환

    @staticmethod
    def backward(ctx, grad_output):
        # 그래디언트의 부호를 뒤집고 alpha를 곱함
        grad_input = -ctx.alpha * grad_output 
        return grad_input, None # alpha 자체의 그래디언트는 없음

class GradientReversalLayer(nn.Module):
    def __init__(self, alpha):
        super(GradientReversalLayer, self).__init__()
        self.alpha = alpha

    def forward(self, input):
        # autograd Function을 적용
        return GradientReversalFunction.apply(input, self.alpha)

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (torch.Tensor, float, float, float, float) -> torch.Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)






# ## --------------------------------------------------------
# RMSNorm
# 기존의 LayerNorm의 계산 복잡도를 줄이고 성능은 유지한다.
# Simba 논문에서 참고했다.
# ## --------------------------------------------------------
class RMSNorm(nn.Module):
    def __init__(self, d, eps=1e-6):
        super().__init__()
        self.eps = eps
        # >> 감마(gamma)에 해당하는 학습 가능한 가중치이다.
        self.weight = nn.Parameter(torch.ones(d))

    def forward(self, x):
        # >> 입력 x의 마지막 차원에 대해 RMS(Root Mean Square)를 계산하고 정규화한다.
        # x * (1 / sqrt(mean(x^2) + eps)) * weight
        rsqrt = torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + self.eps)
        return x * rsqrt * self.weight
    




# ## ------------------------------------------------------------
# Attention Pooling
# 시퀀스 데이터의 각 요소에 어텐션 가중치를 부여한다.
# 중요한 정보만 압축하여 하나의 context vector를 생성한다.
# ## ------------------------------------------------------------
class AttentionPooling(nn.Module):
    def __init__(self, d_model):
        super().__init__()
        # >> 입력 특징(d_model)을 받아 1개의 어텐션 점수로 변환하는 선형 레이어
        self.attention_scorer = nn.Linear(d_model, 1)

    def forward(self, x):
        # x shape: (N, T, J, C)
        N, T, J, C = x.shape

        # >> 1. 어텐션 점수 계산을 위해 (N, T*J, C) 형태로 변경한다.
        x_reshaped = x.view(N, T * J, C)

        # >> 2. 각 위치(T*J개)의 중요도를 계산한다.
        # (N, T*J, C) -> (N, T*J, 1)
        attention_logits = self.attention_scorer(x_reshaped)

        # >> 3. Softmax를 적용하여 합이 1인 어텐션 가중치 생성한다.
        # (N, T*J, 1)
        attention_weights = torch.softmax(attention_logits, dim=1)

        # >> 4. 가중치와 원래 특징을 곱하여 가중 합(weighted sum) 계산한다.
        # (N, T*J, C) * (N, T*J, 1) -> (N, T*J, C)
        # .sum(dim=1)을 통해 (N, C) 형태의 최종 요약 벡터 생성
        context_vector = (x_reshaped * attention_weights).sum(dim=1)

        return context_vector
    

# ## ------------------------------------------------------------
# 2D 학습 가능 Positional Encoding
# 시간(T)과 공간(J)을 위한 별도의 학습 가능한 임베딩을 사용합니다.
# ## ------------------------------------------------------------
class SpatioTemporalPositionalEncoding(nn.Module):
    def __init__(self, d_model: int, num_joints: int, max_frames: int, dropout: float = 0.2):
        super().__init__()
        self.dropout = nn.Dropout(p=dropout)
        
        # (1, T, 1, C) 형태의 학습 가능한 시간적(temporal) PE
        self.temporal_pe = nn.Parameter(torch.zeros(1, max_frames, 1, d_model))
        # (1, 1, J, C) 형태의 학습 가능한 공간적(spatial) PE
        self.spatial_pe = nn.Parameter(torch.zeros(1, 1, num_joints, d_model))

        # Hyperformer의 방식대로 trunc_normal_로 초기화
        trunc_normal_(self.temporal_pe, std=.02)
        trunc_normal_(self.spatial_pe, std=.02)

    def forward(self, x):
        # x shape: (N, T, J, C)
        
        # 시간 PE 더하기 (N과 J 차원에 대해 브로드캐스팅됨)
        # x.size(1)은 실제 T_fast 또는 T_slow 길이
        x = x + self.temporal_pe[:, :x.size(1), :, :]
        
        # 공간 PE 더하기 (N과 T 차원에 대해 브로드캐스팅됨)
        # x.size(2)는 실제 J (50)
        x = x + self.spatial_pe[:, :, :x.size(2), :]
        
        return self.dropout(x)







# ## -------------------------------------------------------------------------
# Spatial-Temporal Transformer Block
# Shift-GCN 이후, 공간(Spatial) 축과 시간(Temporal) 축에 대해
# 순차적으로 Transformer 어텐션을 적용하여 시공간 특징을 분리하여 학습한다.
# ## -------------------------------------------------------------------------
class ST_Transformer_Block(nn.Module):
    def __init__(self, in_features, out_features, num_joints, nhead=4, dim_feedforward=256):
        super().__init__()

        # >> 차원 변환 표준 레이어다.
        self.input_proj = nn.Linear(in_features, out_features)
        self.norm_proj = RMSNorm(out_features)

        
        # >> Evo-ViT: 공간적 토큰 선택을 위한 [SPATIAL_CLS] 토큰 추가
        self.spatial_cls_token = nn.Parameter(torch.zeros(1, 1, out_features))
        self.spatial_keep_rate = config.SPATIAL_KEEP_RATE
        self.num_joints = num_joints

        # >> Slow Fast
        self.spatial_norm1 = RMSNorm(out_features)
        self.spatial_msa = nn.MultiheadAttention(
            embed_dim=out_features, num_heads=nhead, dropout=0.2, batch_first=True
        )
        self.spatial_norm2 = RMSNorm(out_features)
        self.spatial_ffn = nn.Sequential(
            nn.Linear(out_features, dim_feedforward),
            nn.GELU(),
            nn.Dropout(0.2),
            nn.Linear(dim_feedforward, out_features),
            nn.Dropout(0.2)
        )
        
        # >> Fast Path는 별도 모듈이 없어서 구현하지 않는다.


        # >> 2. 시간적 어텐션을 위한 Transformer 인코더이다.
        temporal_encoder_layer = nn.TransformerEncoderLayer(
            d_model=out_features, nhead=nhead, dim_feedforward=dim_feedforward,
            activation='gelu', batch_first=True, dropout=0.2
        )
        self.temporal_transformer_encoder = nn.TransformerEncoder(temporal_encoder_layer, num_layers=1)
        self.norm_temporal = RMSNorm(out_features)
        

        # >> 3.  잔차 연결이다.
        if in_features != out_features:
            self.residual = nn.Sequential(
                nn.Linear(in_features, out_features),
                RMSNorm(out_features)
            )
        else:
            self.residual = nn.Identity()


    def forward(self, x, prev_spatial_attn_scores=None):
        # x shape: (N, T, J, C)
        # >> C_out을 self.spatial_cls_token에서 가져온다.
        N, T, J, C_out = x.shape[0], x.shape[1], x.shape[2], self.spatial_cls_token.shape[-1]
        
        # >> 잔차 연결을 위해 초기 입력을 저장한다.
        res = self.residual(x)

        # >> 차원 C_in을 C_out으로 변경한다.
        x_proj = self.norm_proj(self.input_proj(x)) # (N, T, J, C_out)

        # >> 공간적 잔차 연결을 위해 프로젝션 결과를 저장한다.
        res_spatial = x_proj
        
        # >> (N, T, J, C) -> (N*T, J, C)
        # >> 프로젝션 출력을 Spatial-Transformer의 입력으로 사용한다.
        x_spatial_in = x_proj.contiguous().view(N * T, J, C_out)
        NT, J, C = x_spatial_in.shape


        # --- 1. Evo-ViT 공간적 토큰 선택 ---
        k = int(J * self.spatial_keep_rate) # 유지할 중요 관절(informative) 수

        if prev_spatial_attn_scores is None:
            # >> 이전 어텐션 맵이 없음 (첫 번째 블록) -> 모든 토큰을 Slow 경로로
            indices_to_keep = torch.arange(J, device=x.device).unsqueeze(0).repeat(NT, 1)
            indices_to_drop = torch.empty(NT, 0, dtype=torch.long, device=x.device)
            # >> 점수도 없으므로 가중치 없는 평균 집계 사용
            placeholder_scores_norm = None 
        else:
            # >> 이전 어텐션 맵을 기반으로 토큰 선택
            scores = prev_spatial_attn_scores # (NT, J)
            all_indices = torch.argsort(scores, dim=1, descending=True)
            indices_to_keep = all_indices[:, :k] # (NT, k)
            indices_to_drop = all_indices[:, k:] # (NT, J-k)
            
            # >> 집계(Aggregation)를 위한 가중치 계산
            placeholder_scores = torch.gather(scores, 1, indices_to_drop)
            placeholder_scores_norm = torch.softmax(placeholder_scores, dim=1).unsqueeze(-1) # (NT, J-k, 1)


        # --- 2. Slow-Fast 토큰 분리 ---
        
        # >> 2-1. 중요 토큰 (Informative tokens)
        # (NT, J, C) -> (NT, k, C)
        x_inf = torch.gather(x_spatial_in, 1, indices_to_keep.unsqueeze(-1).expand(-1, -1, C))
        
        # >> 2-2. 자리 표시자 토큰 (Placeholder tokens)
        # (NT, J, C) -> (NT, J-k, C)
        x_ph = torch.gather(x_spatial_in, 1, indices_to_drop.unsqueeze(-1).expand(-1, -1, C))

        # >> 2-3. 대표 토큰 (Representative token) - 집계
        if prev_spatial_attn_scores is None or k == J:
            x_rep = torch.empty(NT, 0, C, device=x.device) # (첫 블록이거나 모두 keep이면 rep 없음)
        else:
            # 가중 합 (Weighted Sum)
            x_rep = (x_ph * placeholder_scores_norm).sum(dim=1, keepdim=True) # (NT, 1, C)

        # >> 2-4. [SPATIAL_CLS] 토큰 준비
        cls_token = self.spatial_cls_token.repeat(NT, 1, 1) # (NT, 1, C)
        
        # >> 2-5. Slow 경로 입력 준비: [CLS, Informative, Representative]
        x_slow_in = torch.cat([cls_token, x_inf, x_rep], dim=1) # (NT, 1+k+1 또는 1+k, C)

        # --- 3. Slow 경로 연산 (MSA + FFN) ---
        
        # >> 3-1. MSA
        x_norm1 = self.spatial_norm1(x_slow_in)
        # average_attn_weights=False (기본값) -> (NT, nhead, L, S) 반환
        attn_output, new_attn_weights = self.spatial_msa(
            x_norm1, x_norm1, x_norm1, average_attn_weights=False
        )
        x_slow_msa_out = x_slow_in + attn_output # (잔차 연결 1)
        
        # >> 3-2. FFN
        x_norm2 = self.spatial_norm2(x_slow_msa_out)
        ffn_output = self.spatial_ffn(x_norm2)
        x_slow_final = x_slow_msa_out + ffn_output # (잔차 연결 2)

        # --- 4. 다음 레이어를 위한 어텐션 맵 추출 ---
        # (NT, nhead, 1+k+..., 1+k+...)
        # CLS 토큰(idx 0)이 다른 토큰(idx 1:)에 부여한 어텐션
        next_cls_attn_to_others = new_attn_weights[:, :, 0, 1:].mean(dim=1) # (NT, k+1 또는 k)

        next_spatial_attn = torch.zeros(NT, J, device=x.device, dtype=x.dtype)
        
        # 중요 토큰(informative)에 대한 어텐션 점수
        cls_attn_to_inf = next_cls_attn_to_others[:, :indices_to_keep.shape[1]]
        next_spatial_attn.scatter_(1, indices_to_keep, cls_attn_to_inf)
        
        if prev_spatial_attn_scores is not None and k != J:
            # 대표 토큰(representative)에 대한 어텐션 점수
            cls_attn_to_rep = next_cls_attn_to_others[:, k:] # (NT, 1)
            # 대표 점수를 모든 자리 표시자(placeholder) 토큰에 전파
            next_spatial_attn.scatter_(1, indices_to_drop, cls_attn_to_rep.expand(-1, J-k))


        # --- 5. Fast 경로 연산 (확장)  ---
        
        if prev_spatial_attn_scores is None or k == J:
            x_ph_out = x_ph # (첫 블록이거나 모두 keep이면 fast update 없음)
        else:
            # >> 5-1. Slow 경로에서 대표 토큰의 '잔차'만 추출
            msa_res_rep = attn_output[:, 1+k:, :]
            ffn_res_rep = ffn_output[:, 1+k:, :]
            x_rep_res_combined = msa_res_rep + ffn_res_rep # (NT, 1, C)

            # >> 5-2. 잔차를 모든 자리 표시자 토큰에 더함
            x_ph_out = x_ph + x_rep_res_combined.expand(-1, J-k, -1) # (NT, J-k, C)
            
        # --- 6. 전체 텐서 재구성 (Scatter) ---
        num_inf_tokens = indices_to_keep.shape[1]
        x_inf_out = x_slow_final[:, 1:1 + num_inf_tokens, :]
        
        x_spatial_out = torch.zeros_like(x_spatial_in)
        x_spatial_out.scatter_(1, indices_to_keep.unsqueeze(-1).expand(-1, -1, C), x_inf_out)
        x_spatial_out.scatter_(1, indices_to_drop.unsqueeze(-1).expand(-1, -1, C), x_ph_out)
        
        # >> (N*T, J, C) -> (N, T, J, C)
        x_spatial_out = x_spatial_out.view(N, T, J, C_out)

        # >> 프로젝션 잔차를 더한다.
        x_spatial_out = x_spatial_out + res_spatial


        # >> 7. 시간 Transformer 어텐션
        x_reshaped_temporal = x_spatial_out.permute(0, 2, 1, 3).contiguous().view(N * J, T, C_out)
        x_temporal_attn = self.temporal_transformer_encoder(x_reshaped_temporal)


        # >> 원래 형태로 복원
        x_temporal_out = x_temporal_attn.view(N, J, T, C_out).permute(0, 2, 1, 3).contiguous()


        # >> 8. 최종 잔차 연결
        x_final = x_temporal_out + res

        # >> (최종 결과, 다음 블록용 어텐션 맵) 반환
        return x_final, next_spatial_attn
    
    

# ## -------------------------------------------------------------------------
# SlowFast Transformer
# GCN-Transformer 컴포넌트를 재사용하여 비대칭적인 2-스트림 모델을 구현한다.
# - Fast Pathway: 가벼운 네트워크로 높은 시간 해상도를 처리 (2프레임 간격)
# - Slow Pathway: 무거운 네트워크로 낮은 시간 해상도를 처리 (4프레임 간격)
# ## -------------------------------------------------------------------------
class SlowFast_Transformer(nn.Module):
    def __init__(self,
                 num_joints=config.NUM_JOINTS,
                 num_coords=config.NUM_COORDS,
                 num_classes=config.NUM_CLASSES,
                 fast_dims=config.FAST_DIMS,
                 slow_dims=config.SLOW_DIMS,
                 num_subjects=config.NUM_SUBJECTS
                 ):
        super().__init__()
        
        # >> config.py에서 정의된 채널 수를 가져옵니다.
        self.fast_dims = fast_dims
        self.slow_dims = slow_dims
        
        if len(self.fast_dims) != len(self.slow_dims):
            raise ValueError("Fast와 Slow 경로의 블록 수가 동일해야 합니다.")

        # --- 1. Fast Pathway (가벼움) ---
        
        # >> Fast 경로 입력 프로젝션
        self.fast_input_projection = nn.Linear(num_coords, fast_dims[0])
        # >> Fast 경로 위치 인코딩 (Spatio-Temporal)
        self.fast_pos_encoder = SpatioTemporalPositionalEncoding(
            d_model=fast_dims[0],
            num_joints=num_joints,           # 50
            max_frames=config.MAX_FRAMES     # 150
        )
        
        # >> Fast 경로 GCN-Transformer 블록 리스트
        self.fast_blocks = nn.ModuleList()
        for i in range(len(fast_dims) - 1):
            self.fast_blocks.append(
                ST_Transformer_Block(
                    in_features=fast_dims[i],
                    out_features=fast_dims[i+1],
                    num_joints=num_joints
                )
            )

        # --- 2. Slow Pathway (무거움) ---
        
        # >> Slow 경로 입력 프로젝션
        self.slow_input_projection = nn.Linear(num_coords, slow_dims[0])
        # >> Slow 경로 위치 인코딩 (Spatio-Temporal)
        self.slow_pos_encoder = SpatioTemporalPositionalEncoding(
            d_model=slow_dims[0],
            num_joints=num_joints,           # 50
            max_frames=(config.MAX_FRAMES // 2) # 75
        )
        # >> Slow 경로 GCN-Transformer 블록 리스트
        self.slow_blocks = nn.ModuleList()
        for i in range(len(slow_dims) - 1):
            self.slow_blocks.append(
                ST_Transformer_Block(
                    in_features=slow_dims[i],
                    out_features=slow_dims[i+1],
                    num_joints=num_joints
                )
            )

        # --- 3. Lateral Connection (Fast -> Slow 융합) ---
        
        # >> nn.ModuleList로 변경하여 다단계 융합을 지원합니다.
        self.lateral_connections = nn.ModuleList()

        for i in range(len(self.fast_dims)-1):
            # i=0: in=32, out=128 (Block 0 입력 전 1차 융합)
            # i=1: in=32, out=128 (Block 1 입력 전 2차 융합)
            self.lateral_connections.append(
                nn.Conv2d(
                    in_channels=fast_dims[i],    # Fast 경로의 [i]번째 채널 수
                    out_channels=slow_dims[i],   # Slow 경로의 [i]번째 채널 수
                    kernel_size=(5, 1),      # (Temporal_Kernel=5, Spatial_Kernel=1)
                    stride=(2, 1),           # (Temporal_Stride=2, Spatial_Stride=1)
                    padding=(2, 0)           # (Temporal_Padding=2, Spatial_Padding=0)
                )
            )

        # --- 4. Final Classification (최종 분류) ---
        
        # >> 각 경로의 최종 특징 차원
        final_fast_dim = fast_dims[-1]
        final_slow_dim = slow_dims[-1]

        # >> 융합된 특징 차원을 먼저 정의한다.
        combined_dim = final_fast_dim + final_slow_dim

        # >> 각 경로에 대한 어텐션 풀링
        self.fast_pool = AttentionPooling(d_model=final_fast_dim)
        self.slow_pool = AttentionPooling(d_model=final_slow_dim)

        # >> 통합된 행동 분류 헤드 (Head A)
        # >> GRL이 최적화할 융합 벡터(combined_dim)를 입력으로 받습니다.
        self.action_head = nn.Sequential(
            nn.Dropout(p=config.DROPOUT),
            nn.Linear(combined_dim, num_classes) # 320 -> 60
        )
        
        # >> 1. Gradient Reversal Layer (GRL) 인스턴스 생성
        # >> alpha 값은 config에서 불러옴
        self.grad_reversal = GradientReversalLayer(alpha=1.0) 
        
        # >> 2. 피실험자 분류기 (Head B) 정의 
        self.subject_classifier = nn.Sequential(
            nn.Linear(combined_dim, 256), # 두 스트림의 정보를 합쳐서 받음
            nn.GELU(),
            RMSNorm(256),
            nn.Dropout(p=config.DROPOUT),
            nn.Linear(256, num_subjects) # config의 NUM_SUBJECTS로 예측
        )

    
    def forward(self, x_fast, x_slow):
        # x_fast shape: (N, C, T_fast, J)
        # x_slow shape: (N, C, T_slow, J)
        
        N, _, T_fast, J = x_fast.shape
        _, _, T_slow, _ = x_slow.shape

        # --- 1. 입력 Permute (N, C, T, J) -> (N, T, J, C) ---
        x_fast = x_fast.permute(0, 2, 3, 1).contiguous()
        x_slow = x_slow.permute(0, 2, 3, 1).contiguous()
        
        # --- 2. Fast 경로 처리 (PE 추가) ---
        x_fast = self.fast_input_projection(x_fast) # (N, T_fast, J, C_fast0)
        
        # (N, T, J, C)에 2D PE를 직접 적용
        x_fast = self.fast_pos_encoder(x_fast) # (N, T_fast, J, C_fast0)

        x_slow = self.slow_input_projection(x_slow)
        # (N, T, J, C)에 2D PE를 직접 적용
        x_slow = self.slow_pos_encoder(x_slow) # (N, T_slow, J, C_slow0)
        
        # --- 4. GCN-Transformer 블록 및 다단계 융합 처리 ---
        fast_attn_map = None # (N*T_fast, J)
        slow_attn_map = None # (N*T_slow, J)

        # len(self.fast_blocks)는 2 (i=0, i=1)
        for i in range(len(self.fast_blocks)):
            
            # --- A. 융합 수행 (Lateral Connection) ---
            # (N, T, J, C_fast) -> (N, C_fast, T, J)
            x_fast_for_lat = x_fast.permute(0, 3, 1, 2).contiguous()
            
            # [Conv2D] (N, C_fast_i, T_fast, J) -> (N, C_slow_i, T_slow, J)
            # i=0일 때: lateral_connections[0] (1차 융합)
            # i=1일 때: lateral_connections[1] (2차 융합)
            x_fused = self.lateral_connections[i](x_fast_for_lat)
            
            # (N, C_slow_i, T_slow, J) -> (N, T_slow, J, C_slow_i)
            x_fused = x_fused.permute(0, 2, 3, 1).contiguous()

            # [핵심 융합] Slow 경로에 Fast 경로의 정보를 더합니다.
            x_slow = x_slow + x_fused
            
            
            # --- B. GCN-Transformer 블록 실행 ---
            x_fast, fast_attn_map = self.fast_blocks[i](x_fast, fast_attn_map)
            x_slow, slow_attn_map = self.slow_blocks[i](x_slow, slow_attn_map)
            
        # --- 5. 최종 풀링 및 분류 ---
        summary_fast = self.fast_pool(x_fast) # (N, C_fast_final)
        summary_slow = self.slow_pool(x_slow) # (N, C_slow_final)

        # >> 두 요약 벡터를 먼저 연결하여 융합 특징을 생성한다.
        combined_summary = torch.cat([summary_slow, summary_fast], dim=1)
        
        # >> Head A: 융합된 특징으로 행동을 예측한다.
        output_action = self.action_head(combined_summary)

        # >> [Head B] 피실험자 예측
        # >> 동일한 융합 특징을 GRL에 통과시킨다.
        reversed_features = self.grad_reversal(combined_summary)
        output_subject = self.subject_classifier(reversed_features)


        return output_action, output_subject
    
