# model.py
# ## ------------------------------------------------------------
#
# ## ------------------------------------------------------------


import torch
import torch.nn as nn
import numpy as np
import config
import math
from torch.autograd import Function
import warnings

# ## -----------------------------------------------------------------
# Gradient Reversal Layer (GRL)
# ## -----------------------------------------------------------------
class GradientReversalFunction(Function):
    @staticmethod
    def forward(ctx, input, alpha):
        # alpha 값을 저장하여 backward에서 사용
        ctx.alpha = alpha 
        return input.clone() # 입력 그대로 반환

    @staticmethod
    def backward(ctx, grad_output):
        # 그래디언트의 부호를 뒤집고 alpha를 곱함
        grad_input = -ctx.alpha * grad_output 
        return grad_input, None # alpha 자체의 그래디언트는 없음

class GradientReversalLayer(nn.Module):
    def __init__(self, alpha):
        super(GradientReversalLayer, self).__init__()
        self.alpha = alpha

    def forward(self, input):
        # autograd Function을 적용
        return GradientReversalFunction.apply(input, self.alpha)

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (torch.Tensor, float, float, float, float) -> torch.Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)






# ## --------------------------------------------------------
# RMSNorm
# 기존의 LayerNorm의 계산 복잡도를 줄이고 성능은 유지한다.
# Simba 논문에서 참고했다.
# ## --------------------------------------------------------
class RMSNorm(nn.Module):
    def __init__(self, d, eps=1e-6):
        super().__init__()
        self.eps = eps
        # >> 감마(gamma)에 해당하는 학습 가능한 가중치이다.
        self.weight = nn.Parameter(torch.ones(d))

    def forward(self, x):
        # >> 입력 x의 마지막 차원에 대해 RMS(Root Mean Square)를 계산하고 정규화한다.
        # x * (1 / sqrt(mean(x^2) + eps)) * weight
        rsqrt = torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + self.eps)
        return x * rsqrt * self.weight
    




# ## ------------------------------------------------------------
# Attention Pooling
# 시퀀스 데이터의 각 요소에 어텐션 가중치를 부여한다.
# 중요한 정보만 압축하여 하나의 context vector를 생성한다.
# ## ------------------------------------------------------------
class AttentionPooling(nn.Module):
    def __init__(self, d_model):
        super().__init__()
        # >> 입력 특징(d_model)을 받아 1개의 어텐션 점수로 변환하는 선형 레이어
        self.attention_scorer = nn.Linear(d_model, 1)

    def forward(self, x):
        # x shape: (N, T, J, C)
        N, T, J, C = x.shape

        # >> 1. 어텐션 점수 계산을 위해 (N, T*J, C) 형태로 변경한다.
        x_reshaped = x.view(N, T * J, C)

        # >> 2. 각 위치(T*J개)의 중요도를 계산한다.
        # (N, T*J, C) -> (N, T*J, 1)
        attention_logits = self.attention_scorer(x_reshaped)

        # >> 3. Softmax를 적용하여 합이 1인 어텐션 가중치 생성한다.
        # (N, T*J, 1)
        attention_weights = torch.softmax(attention_logits, dim=1)

        # >> 4. 가중치와 원래 특징을 곱하여 가중 합(weighted sum) 계산한다.
        # (N, T*J, C) * (N, T*J, 1) -> (N, T*J, C)
        # .sum(dim=1)을 통해 (N, C) 형태의 최종 요약 벡터 생성
        context_vector = (x_reshaped * attention_weights).sum(dim=1)

        return context_vector
    

# ## ------------------------------------------------------------
# 2D 학습 가능 Positional Encoding
# 시간(T)과 공간(J)을 위한 별도의 학습 가능한 임베딩을 사용합니다.
# ## ------------------------------------------------------------
class SpatioTemporalPositionalEncoding(nn.Module):
    def __init__(self, d_model: int, num_joints: int, max_frames: int, dropout: float = 0.2):
        super().__init__()
        self.dropout = nn.Dropout(p=dropout)
        
        # (1, T, 1, C) 형태의 학습 가능한 시간적(temporal) PE
        self.temporal_pe = nn.Parameter(torch.zeros(1, max_frames, 1, d_model))
        # (1, 1, J, C) 형태의 학습 가능한 공간적(spatial) PE
        self.spatial_pe = nn.Parameter(torch.zeros(1, 1, num_joints, d_model))

        # Hyperformer의 방식대로 trunc_normal_로 초기화
        trunc_normal_(self.temporal_pe, std=.02)
        trunc_normal_(self.spatial_pe, std=.02)

    def forward(self, x):
        # x shape: (N, T, J, C)
        
        # 시간 PE 더하기 (N과 J 차원에 대해 브로드캐스팅됨)
        # x.size(1)은 실제 T_fast 또는 T_slow 길이
        x = x + self.temporal_pe[:, :x.size(1), :, :]
        
        # 공간 PE 더하기 (N과 T 차원에 대해 브로드캐스팅됨)
        # x.size(2)는 실제 J (50)
        x = x + self.spatial_pe[:, :, :x.size(2), :]
        
        return self.dropout(x)







# ## -------------------------------------------------------------------------
# Spatial-Temporal Transformer Block
# Shift-GCN 이후, 공간(Spatial) 축과 시간(Temporal) 축에 대해
# 순차적으로 Transformer 어텐션을 적용하여 시공간 특징을 분리하여 학습한다.
# ## -------------------------------------------------------------------------
class ST_Transformer_Block(nn.Module):
    def __init__(self, in_features, out_features, num_joints, nhead=4, pos_encoder=None):
        super().__init__()
        self.out_features = out_features

        dim_feedforward = out_features * 2

        self.pos_encoder = pos_encoder
        
        # >> 차원 변환 표준 레이어다.
        self.input_proj = nn.Linear(in_features, out_features)
        self.norm_proj = RMSNorm(out_features)

        
        self.num_joints = num_joints

        # >> Slow Fast
        self.spatial_norm1 = RMSNorm(out_features)
        self.spatial_msa = nn.MultiheadAttention(
            embed_dim=out_features, num_heads=nhead, dropout=0.2, batch_first=True
        )
        self.spatial_norm2 = RMSNorm(out_features)
        self.spatial_ffn = nn.Sequential(
            nn.Linear(out_features, dim_feedforward),
            nn.GELU(),
            nn.Dropout(0.2),
            nn.Linear(dim_feedforward, out_features),
            nn.Dropout(0.2)
        )


        # >> 2. 시간적 어텐션을 위한 Transformer 인코더이다.
        temporal_encoder_layer = nn.TransformerEncoderLayer(
            d_model=out_features, nhead=nhead, dim_feedforward=dim_feedforward,
            activation='gelu', batch_first=True, dropout=0.2
        )
        self.temporal_transformer_encoder = nn.TransformerEncoder(temporal_encoder_layer, num_layers=1)
        self.norm_temporal = RMSNorm(out_features)
        

        # >> 3.  잔차 연결이다.
        if in_features != out_features:
            self.residual = nn.Sequential(
                nn.Linear(in_features, out_features),
                RMSNorm(out_features)
            )
        else:
            self.residual = nn.Identity()


    def forward(self, x):
        # x shape: (N, T, J, C)
        # >> C_out을 self.spatial_cls_token에서 가져온다.
        N, T, J, C_out = x.shape[0], x.shape[1], x.shape[2], self.out_features
        
        # >> 잔차 연결을 위해 초기 입력을 저장한다.
        res = self.residual(x)

        # >> 차원 C_in을 C_out으로 변경한다.
        x_proj = self.norm_proj(self.input_proj(x)) # (N, T, J, C_out)

        # >> PE를 적용한다.
        if self.pos_encoder is not None:
            x_proj = self.pos_encoder(x_proj)

        # >> 공간적 잔차 연결을 위해 프로젝션 결과를 저장한다.
        res_spatial = x_proj
        
        # >> (N, T, J, C) -> (N*T, J, C)
        # >> 프로젝션 출력을 Spatial-Transformer의 입력으로 사용한다.
        x_spatial_in = x_proj.contiguous().view(N * T, J, C_out)
        NT, J, C = x_spatial_in.shape

        # >> MSA
        x_norm1 = self.spatial_norm1(x_spatial_in)
        # >> 
        attn_output, _ = self.spatial_msa(
            x_norm1, x_norm1, x_norm1, average_attn_weights=False
        )
        x_msa_out = x_spatial_in + attn_output # (잔차 연결 1)


        
        # >> FFN
        x_norm2 = self.spatial_norm2(x_msa_out)
        ffn_output = self.spatial_ffn(x_norm2)
        x_spatial_out_NT = x_msa_out + ffn_output # (잔차 연결 2)

        
        # >> (N*T, J, C) -> (N, T, J, C)
        x_spatial_out = x_spatial_out_NT.view(N, T, J, C_out)




        

        # >> 시간 Transformer 어텐션
        x_reshaped_temporal = x_spatial_out.permute(0, 2, 1, 3).contiguous().view(N * J, T, C_out)
        x_temporal_attn = self.temporal_transformer_encoder(x_reshaped_temporal)


        # >> 원래 형태로 복원
        x_temporal_out = x_temporal_attn.view(N, J, T, C_out).permute(0, 2, 1, 3).contiguous()


        # >> (최종 결과, 다음 블록용 어텐션 맵) 반환
        return x_temporal_out + res
    
    

# ## -------------------------------------------------------------------------
# SlowFast Transformer
# Transformer 컴포넌트를 재사용하여 비대칭적인 2-스트림 모델을 구현한다.
# - Fast Pathway: 가벼운 네트워크로 높은 시간 해상도를 처리 (2프레임 간격)
# - Slow Pathway: 무거운 네트워크로 낮은 시간 해상도를 처리 (4프레임 간격)
# ## -------------------------------------------------------------------------
class SlowFast_Transformer(nn.Module):
    def __init__(self,
                 num_joints=config.NUM_JOINTS,
                 num_coords=config.NUM_COORDS,
                 num_classes=config.NUM_CLASSES,
                 fast_dims=config.FAST_DIMS,
                 slow_dims=config.SLOW_DIMS,
                 num_subjects=config.NUM_SUBJECTS,
                 alpha=1.0
                 ):
        super().__init__()
        
        # >> config.py에서 정의된 채널 수를 가져옵니다.
        self.fast_dims = fast_dims
        self.slow_dims = slow_dims
        
        if len(self.fast_dims) != len(self.slow_dims):
            raise ValueError("Fast와 Slow 경로의 블록 수가 동일해야 합니다.")

        # --- 1. Fast Pathway (가벼움) ---
        
        # >> Fast 경로 입력 프로젝션
        self.fast_input_projection = nn.Linear(num_coords, fast_dims[0])
        
        
        # >> Fast 경로 GCN-Transformer 블록 리스트
        self.fast_blocks = nn.ModuleList()
        for i in range(len(fast_dims) - 1):
            # >> 각 블록에 맞는 PE를 생성하기
            fast_pe = SpatioTemporalPositionalEncoding(
                d_model=fast_dims[i+1],
                num_joints=num_joints,
                max_frames=config.MAX_FRAMES
            )

            
            self.fast_blocks.append(
                ST_Transformer_Block(
                    in_features=fast_dims[i],
                    out_features=fast_dims[i+1],
                    num_joints=num_joints,
                    pos_encoder=fast_pe
                )
            )

        # --- 2. Slow Pathway (무거움) ---
        
        # >> Slow 경로 입력 프로젝션
        self.slow_input_projection = nn.Linear(num_coords, slow_dims[0])

        # >> Slow 경로 GCN-Transformer 블록 리스트
        self.slow_blocks = nn.ModuleList()

        for i in range(len(slow_dims) - 1):
            # >> PE를 생성하기.
            slow_pe = SpatioTemporalPositionalEncoding(
                d_model=slow_dims[i+1],
                num_joints=num_joints,
                max_frames=(config.MAX_FRAMES // 2)
            )
            
            self.slow_blocks.append(
                ST_Transformer_Block(
                    in_features=slow_dims[i],
                    out_features=slow_dims[i+1],
                    num_joints=num_joints,
                    pos_encoder=slow_pe
                )
            )

        # --- 3. Lateral Connection (Fast -> Slow 융합) ---
        
        # >> nn.ModuleList로 변경하여 다단계 융합을 지원합니다.
        self.lateral_connections = nn.ModuleList()

        for i in range(len(self.fast_dims)-1):
            # i=0: in=32, out=128 (Block 0 입력 전 1차 융합)
            # i=1: in=32, out=128 (Block 1 입력 전 2차 융합)
            self.lateral_connections.append(
                nn.Conv2d(
                    in_channels=fast_dims[i],    # Fast 경로의 [i]번째 채널 수
                    out_channels=slow_dims[i],   # Slow 경로의 [i]번째 채널 수
                    kernel_size=(5, 1),      # (Temporal_Kernel=5, Spatial_Kernel=1)
                    stride=(2, 1),           
                    padding=(2, 0)           # (Temporal_Padding=2, Spatial_Padding=0)
                )
            )

        # --- 4. Final Classification (최종 분류) ---
        
        # >> 각 경로의 최종 특징 차원
        final_fast_dim = fast_dims[-1]
        final_slow_dim = slow_dims[-1]

        # >> 융합된 특징 차원을 먼저 정의한다.
        combined_dim = final_fast_dim + final_slow_dim

        # >> 각 경로에 대한 어텐션 풀링
        self.fast_pool = AttentionPooling(d_model=final_fast_dim)
        self.slow_pool = AttentionPooling(d_model=final_slow_dim)

        # >> 통합된 행동 분류 헤드 (Head A)
        # >> GRL이 최적화할 융합 벡터(combined_dim)를 입력으로 받습니다.
        self.action_head = nn.Sequential(
            nn.Dropout(p=config.DROPOUT),
            nn.Linear(combined_dim, num_classes) # 320 -> 60
        )
        
        # >> 1. Gradient Reversal Layer (GRL) 인스턴스 생성
        # >> alpha 값은 config에서 불러옴
        self.grad_reversal = GradientReversalLayer(alpha=alpha) 
        
        # >> 2. 피실험자 분류기 (Head B) 정의 
        self.subject_classifier = nn.Sequential(
            nn.Linear(combined_dim, 256), # 두 스트림의 정보를 합쳐서 받음
            nn.GELU(),
            RMSNorm(256),
            nn.Dropout(p=config.DROPOUT),
            nn.Linear(256, num_subjects) # config의 NUM_SUBJECTS로 예측
        )

    
    def forward(self, x_fast, x_slow):
        # x_fast shape: (N, C, T_fast, J)
        # x_slow shape: (N, C, T_slow, J)
        
        N, _, T_fast, J = x_fast.shape
        _, _, T_slow, _ = x_slow.shape

        # --- 1. 입력 Permute (N, C, T, J) -> (N, T, J, C) ---
        x_fast = x_fast.permute(0, 2, 3, 1).contiguous()
        x_slow = x_slow.permute(0, 2, 3, 1).contiguous()
        
        # --- 2. Fast 경로 처리 (PE 추가) ---
        x_fast = self.fast_input_projection(x_fast) # (N, T_fast, J, C_fast0)
        
        

        x_slow = self.slow_input_projection(x_slow)
        
        

        # len(self.fast_blocks)는 2 (i=0, i=1)
        for i in range(len(self.fast_blocks)):
            
            # --- A. 융합 수행 (Lateral Connection) ---
            # (N, T, J, C_fast) -> (N, C_fast, T, J)
            x_fast_for_lat = x_fast.permute(0, 3, 1, 2).contiguous()
            
            # [Conv2D] (N, C_fast_i, T_fast, J) -> (N, C_slow_i, T_slow, J)
            # i=0일 때: lateral_connections[0] (1차 융합)
            # i=1일 때: lateral_connections[1] (2차 융합)
            x_fused = self.lateral_connections[i](x_fast_for_lat)
            
            # (N, C_slow_i, T_slow, J) -> (N, T_slow, J, C_slow_i)
            x_fused = x_fused.permute(0, 2, 3, 1).contiguous()

            # Slow 경로에 Fast 경로의 정보를 더합니다.
            x_slow = x_slow + x_fused
            
            
            # --- B. GCN-Transformer 블록 실행 ---
            x_fast = self.fast_blocks[i](x_fast)
            x_slow = self.slow_blocks[i](x_slow)
            
        # --- 5. 최종 풀링 및 분류 ---
        summary_fast = self.fast_pool(x_fast) # (N, C_fast_final)
        summary_slow = self.slow_pool(x_slow) # (N, C_slow_final)

        # >> 두 요약 벡터를 먼저 연결하여 융합 특징을 생성한다.
        combined_summary = torch.cat([summary_slow, summary_fast], dim=1)
        
        # >> Head A: 융합된 특징으로 행동을 예측한다.
        output_action = self.action_head(combined_summary)

        # >> [Head B] 피실험자 예측
        # >> 동일한 융합 특징을 GRL에 통과시킨다.
        reversed_features = self.grad_reversal(combined_summary)
        output_subject = self.subject_classifier(reversed_features)


        return output_action, output_subject
    
